baseURL = "https://gsoc.wukovitsch.com"
theme = 'hugo-bearblog'

title = "Google Summer of Code"
author = "Tobias Wukovitsch"
copyright = "Copyright © 2024, Tobias Wukovitsch."
languageCode = "en-US"

enableRobotsTXT = true

enableEmoji = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  pages = "/:slug/"

[params]
  title = "Google Summer of Code"
  description = "This a personal collection of documents related to GSoC."
  favicon = "images/favicon.png"
  hideMadeWithLine = true